"$schema" = "./node_modules/wrangler/config-schema.json"
compatibility_date = "2026-03-10"
main = ".eleventy.js"
name = "personal-site"
workers_dev = false

[build]
command = "npm run build"

[assets]
directory = "./dist"
